cloudflare_api_token           = "your-cf-api-token"
cloudflare_account_id          = "your-cf-account-id"
cloudflare_zone_id             = "your-cf-zone-id"
tunnel_name                    = "your-cf-tunnel-name"
application_name               = "your-cf-app-name"
application_domain             = "subdomain.your-domain.com"
application_service_token_name = "your-cf-app-service-token-name"
